
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat May 05 03:16:35 ICT 2018
//----------------------------------------------------

package rcalc.parsers;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MULTIPLY = 4;
  public static final int ASSIGNOP = 16;
  public static final int PLUS = 2;
  public static final int RPAREN = 8;
  public static final int ENDSTMT = 19;
  public static final int IDENTIFIER = 10;
  public static final int WHILEOP = 18;
  public static final int LPAREN = 7;
  public static final int EXP = 6;
  public static final int DECLOP = 15;
  public static final int LOGICALOP = 12;
  public static final int TYPE = 11;
  public static final int EOF = 0;
  public static final int NUMBER = 9;
  public static final int DIVIDE = 5;
  public static final int MINUS = 3;
  public static final int error = 1;
  public static final int BLOCKOPEN = 13;
  public static final int IFOP = 17;
  public static final int BLOCKCLOSE = 14;
}

