
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat May 05 23:00:20 ICT 2018
//----------------------------------------------------

package alang.parsers;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MULTIPLY = 4;
  public static final int ASSIGNOP = 15;
  public static final int PLUS = 2;
  public static final int RPAREN = 8;
  public static final int CHAR = 24;
  public static final int ENDSTMT = 19;
  public static final int IDENTIFIER = 9;
  public static final int WHILEOP = 18;
  public static final int REALNUM = 23;
  public static final int LPAREN = 7;
  public static final int EXP = 6;
  public static final int DECLOP = 14;
  public static final int LOGICALOP = 11;
  public static final int BOOLEAN = 25;
  public static final int TYPE = 10;
  public static final int PRINTOP = 20;
  public static final int EOF = 0;
  public static final int DIVIDE = 5;
  public static final int MINUS = 3;
  public static final int error = 1;
  public static final int BLOCKOPEN = 12;
  public static final int IFOP = 17;
  public static final int INDEXOP = 16;
  public static final int INTNUM = 22;
  public static final int SEPERATOR = 21;
  public static final int BLOCKCLOSE = 13;
}

